/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Action_redirect: typeof import('./src/components/action_redirect/index.vue')['default']
    Address: typeof import('./src/components/address/index.vue')['default']
    Appointment: typeof import('./src/components/appointment/index.vue')['default']
    Audio_recorder: typeof import('./src/components/audio_recorder/index.vue')['default']
    Button: typeof import('primevue/button')['default']
    Captcha: typeof import('./src/components/captcha/index.vue')['default']
    Checkboxes: typeof import('./src/components/checkboxes/index.vue')['default']
    Code_javascript: typeof import('./src/components/code_javascript/index.vue')['default']
    Code_json: typeof import('./src/components/code_json/index.vue')['default']
    Color_picker: typeof import('./src/components/color_picker/index.vue')['default']
    Consent_checkbox: typeof import('./src/components/consent_checkbox/index.vue')['default']
    Data_table: typeof import('./src/components/data_table/index.vue')['default']
    Date_picker: typeof import('./src/components/date_picker/index.vue')['default']
    Dropdown: typeof import('./src/components/dropdown/index.vue')['default']
    Email: typeof import('./src/components/email/index.vue')['default']
    Embed_document: typeof import('./src/components/embed_document/index.vue')['default']
    Embed_slides: typeof import('./src/components/embed_slides/index.vue')['default']
    File_upload: typeof import('./src/components/file_upload/index.vue')['default']
    FileCard: typeof import('./src/components/file_upload/file-card.vue')['default']
    Geolocation: typeof import('./src/components/geolocation/index.vue')['default']
    Html_block_content: typeof import('./src/components/html_block_content/index.vue')['default']
    Html_block_list: typeof import('./src/components/html_block_list/index.vue')['default']
    Html_block_media: typeof import('./src/components/html_block_media/index.vue')['default']
    Image_choice: typeof import('./src/components/image_choice/index.vue')['default']
    Likert_scale: typeof import('./src/components/likert_scale/index.vue')['default']
    List: typeof import('./src/components/list/index.vue')['default']
    Locale_selector: typeof import('./src/components/locale_selector/index.vue')['default']
    Long_text: typeof import('./src/components/long_text/index.vue')['default']
    Message: typeof import('primevue/message')['default']
    Multiple_choice: typeof import('./src/components/multiple_choice/index.vue')['default']
    Net_promoter_score: typeof import('./src/components/net_promoter_score/index.vue')['default']
    Number: typeof import('./src/components/number/index.vue')['default']
    Page_break: typeof import('./src/components/page_break/index.vue')['default']
    Password: typeof import('primevue/password')['default']
    Payment: typeof import('./src/components/payment/index.vue')['default']
    Phone_number: typeof import('./src/components/phone_number/index.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    Range: typeof import('./src/components/range/index.vue')['default']
    Ranking: typeof import('./src/components/ranking/index.vue')['default']
    Rating_scale: typeof import('./src/components/rating_scale/index.vue')['default']
    Rich_text: typeof import('./src/components/rich_text/index.vue')['default']
    Short_text: typeof import('./src/components/short_text/index.vue')['default']
    Signature: typeof import('./src/components/signature/index.vue')['default']
    Slider: typeof import('./src/components/slider/index.vue')['default']
    Term_of_service: typeof import('./src/components/term_of_service/index.vue')['default']
    Time_picker: typeof import('./src/components/time_picker/index.vue')['default']
    Website: typeof import('./src/components/website/index.vue')['default']
  }
}
